spring:
  #静态资源处理
  resources:
    #启动默认静态资源处理
    add-mappings: true
    cache:
      cachecontrol:
        #缓存响应式失效时间
        max-age: 3600
    chain:
      #资源连启动缓存
      cache: true
      #启用资源连
      enabled: true
      #启用压缩资源
      compressed: true
      #h5启用缓存
      html-application-cache: true
    static-locations: classpath:/static/
  #thymeleaf配置
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      #连接名
      pool-name: DateHikariCP
      #最小空闲连接出
      minimum-idle: 5
      #空闲连接存货最大时间，默认600000（10分钟）
      idle-timeout: 1800000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从连接池返回的链接是自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活（默认1800000，10分钟）
      max-lifetime: 1800000
      #连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

# redis配置
  redis:
    #服务器地址
    host: 39.103.223.5
    #端口
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大链接数
        max-active: 8
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 200
        # 最大空闲连接，默认0
        min-idle: 5
    password: 123456

# RabbitMQ配置
  rabbitmq:
    #服务器地址
    host: 39.103.223.5
    #用户名
    username: admin
    #密码
    password: 123456
    #虚拟主机
    virtual-host: /
    port: 5672
    #监听
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最小数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完在继续下一跳处理
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重复进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认100ms
        initial-interval: 1000ms
        #重试最大次数，默认3
        max-attempts: 3
        #重试最大时间间隔，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数
        multiplier: 1

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.vector.pojo

#MyBatis SQ打印（方法接口所在的包，不是mapper.xml所在的包
logging:
  level:
    com.vector.mapper: debug
